cc_binary(
    name = "client",
    srcs = [
        "client.cpp",
    ],
    deps = [
        "//src/cli:parser",
        "//src/logging",
        "//src/mychat",
        "//src/protocol:packet",
    ],
)
